services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_DOZZLE:?err}:8080
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_FILTER: status=running
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  dockge_default:
    external: true
